name: plasmabio-template-python
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - jupyterlab>=3
  - nodejs
  - nbresuse
  - psutil
