name: venv
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - jupyterlab>=3.1.*
  - conda-lock
  - setuptools
  - pytorch=1.10.*
  - torchvision
  - torchaudio
  - pyg
  - pytorch-lightning
  - gensim
  - pydot
  - graphviz
  - nltk
  - networkx
  - tensorboardX
  - seaborn
  - nodejs
  - nbresuse
  - psutil
  - pandas
  - pip:
    - lightning-bolts
    - ogb
    - crc32c  # accelerate tensorboardX
    - soundfile # accelerate tensorboardX
    - jupyterlab_latex
    - jupyter-tensorboard
    - jupyterlab-git
    - jupyter-archive
    - jupyterlab-tour
    - ipympl
    - jupyterlab-s3-browser
    