name: graph-torch
# channels priority
# conda-forge has highest prioriy
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pyg
  - gensim
  - pip:
    - pydot
    - python-graphviz
    - pytorch-lightning
    - nltk
