name: venv
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - conda-lock
  - setuptools
  - pytorch=1.10.*
  - torchvision
  - torchaudio
  - pyg
  - pytorch-lightning
  - gensim
  - pydot
  - graphviz
  - nltk
  - networkx
  - tensorboardX
  - seaborn
  - jupyterlab
  - nodejs
  - nbresuse
  - psutil
  - pandas
  - pip:
    - lightning-bolts
    - ogb
    - crc32c  # accelerate tensorboardX
    - soundfile # accelerate tensorboardX
    - jupyterlab_latex
